
name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: https://gogomarket.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: platform/yarn.lock
      
      - name: Install dependencies
        working-directory: ./platform
        run: yarn install --frozen-lockfile
      
      - name: Run database migrations
        working-directory: ./platform
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
      
      - name: Build application
        working-directory: ./platform
        run: yarn build
        env:
          NEXTAUTH_URL: ${{ secrets.PRODUCTION_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
      
      - name: Deploy to hosting
        run: |
          echo "Деплой в продакшн..."
          echo "Настройте интеграцию с вашим хостинг-провайдером"
          echo "Например: Vercel, AWS, DigitalOcean, etc."
      
      - name: Notify deployment success
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'deployment/production',
              description: 'Успешно задеплоено в продакшн'
            })
